all:
  vars:
    ansible_user: admin
    ansible_password: "{{ ansible_password }}"
    ansible_become: true
    ansible_become_method: sudo
    ansible_become_password: "{{ ansible_password }}"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'

prod:
  hosts:
    client:
      ansible_host: 192.168.244.140
  vars:
    env: production

